import { ThemeSettingsDto } from "../types";

export interface PredefinedPalette {
  name: string;
  theme: ThemeSettingsDto;
}

export const predefinedPalettes: PredefinedPalette[] = [
  {
    name: "Predeterminada",
    theme: {
      colorPrimary: "#0077b6",
      colorPrimaryDark: "#023e8a",
      colorPrimaryLight: "#ade8f4",
      colorSecondary: "#eaf8fb",
      colorBackground: "#f4f8f9",
      colorSurface: "#ffffff",
      colorTextPrimary: "#333333",
      colorTextSecondary: "#5a5a5a",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#dce4e8",
      colorBorderLight: "#e8f1f5",
      colorDisabledBg: "#e9ecef",
    },
  },
  {
    name: "Menta Fresca",
    theme: {
      colorPrimary: "#6a994e",
      colorPrimaryDark: "#386641",
      colorPrimaryLight: "#a7c957",
      colorSecondary: "#f2e8cf",
      colorBackground: "#fdfdf6",
      colorSurface: "#ffffff",
      colorTextPrimary: "#2f3e46",
      colorTextSecondary: "#526760",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#e0e0d1",
      colorBorderLight: "#f5f2e9",
      colorDisabledBg: "#f0f0f0",
    },
  },
  {
    name: "Atardecer Coral",
    theme: {
      colorPrimary: "#ff6b6b",
      colorPrimaryDark: "#e55a5a",
      colorPrimaryLight: "#ff9d9d",
      colorSecondary: "#fff0f0",
      colorBackground: "#fff7f7",
      colorSurface: "#ffffff",
      colorTextPrimary: "#4d4d4d",
      colorTextSecondary: "#6b6b6b",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#ffdede",
      colorBorderLight: "#fff5f5",
      colorDisabledBg: "#f2f2f2",
    },
  },
  {
    name: "Océano Profundo",
    theme: {
      colorPrimary: "#58A6FF",
      colorPrimaryDark: "#79B8FF",
      colorPrimaryLight: "#388BFD",
      colorSecondary: "#21262D",
      colorBackground: "#0D1117",
      colorSurface: "#161B22",
      colorTextPrimary: "#E6EDF3",
      colorTextSecondary: "#8B949E",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#30363D",
      colorBorderLight: "#21262D",
      colorDisabledBg: "#21262D",
    },
  },
  {
    name: "Lavanda Relajante",
    theme: {
      colorPrimary: "#9b5de5",
      colorPrimaryDark: "#7b2cbf",
      colorPrimaryLight: "#c77dff",
      colorSecondary: "#f4eaff",
      colorBackground: "#f9f6ff",
      colorSurface: "#ffffff",
      colorTextPrimary: "#3d3d3d",
      colorTextSecondary: "#5e5e5e",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#eadaff",
      colorBorderLight: "#f7f0ff",
      colorDisabledBg: "#edeef2",
    },
  },
  {
    name: "Cítricos Vibrantes",
    theme: {
      colorPrimary: "#fca311",
      colorPrimaryDark: "#e8960e",
      colorPrimaryLight: "#ffb74d",
      colorSecondary: "#fff6e5",
      colorBackground: "#fffaf0",
      colorSurface: "#ffffff",
      colorTextPrimary: "#424242",
      colorTextSecondary: "#616161",
      colorTextOnPrimary: "#000000",
      colorBorder: "#ffeacc",
      colorBorderLight: "#fff9f2",
      colorDisabledBg: "#f5f5f5",
    },
  },
  {
    name: "Borgoña Elegante",
    theme: {
      colorPrimary: "#800f2f",
      colorPrimaryDark: "#590d22",
      colorPrimaryLight: "#c9184a",
      colorSecondary: "#fff0f3",
      colorBackground: "#fef6f8",
      colorSurface: "#ffffff",
      colorTextPrimary: "#333333",
      colorTextSecondary: "#555555",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#ffdde5",
      colorBorderLight: "#fff3f6",
      colorDisabledBg: "#f4e9ec",
    },
  },
  {
    name: "Café y Crema",
    theme: {
      colorPrimary: "#a68a64",
      colorPrimaryDark: "#7f6a4e",
      colorPrimaryLight: "#bfab91",
      colorSecondary: "#f6f3ef",
      colorBackground: "#fbfaf8",
      colorSurface: "#ffffff",
      colorTextPrimary: "#4b443c",
      colorTextSecondary: "#6a625a",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#e6e0d9",
      colorBorderLight: "#f3f0eb",
      colorDisabledBg: "#eaeaea",
    },
  },
  {
    name: "Verde Esmeralda",
    theme: {
      colorPrimary: "#0081a7",
      colorPrimaryDark: "#005f73",
      colorPrimaryLight: "#00a6c1",
      colorSecondary: "#e0f7fa",
      colorBackground: "#f0feff",
      colorSurface: "#ffffff",
      colorTextPrimary: "#222222",
      colorTextSecondary: "#555555",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#ccecf2",
      colorBorderLight: "#e8f8fa",
      colorDisabledBg: "#e9f2f3",
    },
  },
  {
    name: "Minimalista Naranja",
    theme: {
      colorPrimary: "#f4511e",
      colorPrimaryDark: "#d84315",
      colorPrimaryLight: "#ff7043",
      colorSecondary: "#fbe9e7",
      colorBackground: "#fafafa",
      colorSurface: "#ffffff",
      colorTextPrimary: "#333333",
      colorTextSecondary: "#666666",
      colorTextOnPrimary: "#ffffff",
      colorBorder: "#e0e0e0",
      colorBorderLight: "#f5f5f5",
      colorDisabledBg: "#eeeeee",
    },
  },
];
